#pragma once

#include <cbmpc/api/curve.h>
#include <cbmpc/core/buf.h>
#include <cbmpc/core/error.h>

namespace coinbase::api::pve {

// Pluggable base public-key encryption (PKE) used by PVE.
//
// The PVE construction requires *deterministic* encryption given `rho`:
// calling `encrypt(...)` with the same inputs (including the same `rho`) must
// produce the same ciphertext.
//
// Implementations must treat `rho` as the sole source of encryption randomness.
class base_pke_i {
 public:
  virtual ~base_pke_i() = default;

  // Encrypt `plain` under `ek` with associated data `label`, using `rho` as
  // deterministic randomness seed.
  virtual error_t encrypt(mem_t ek, mem_t label, mem_t plain, mem_t rho, buf_t& out_ct) const = 0;

  // Decrypt `ct` under `dk` with associated data `label`.
  virtual error_t decrypt(mem_t dk, mem_t label, mem_t ct, buf_t& out_plain) const = 0;
};

// Built-in base PKE implementation (default).
//
// Key format:
// - `ek` / `dk` are opaque, versioned byte strings generated by:
//   - `generate_base_pke_rsa_keypair(...)`
//   - `generate_base_pke_ecies_p256_keypair(...)`
//
// Notes:
// - The built-in base PKE supports RSA-OAEP(2048) and ECIES(P-256).
// - The base PKE is independent of the curve used by the outer PVE scheme.
const base_pke_i& base_pke_default();

// Generate a keypair for the built-in RSA-OAEP (2048-bit) base PKE.
//
// Outputs are opaque, versioned byte strings compatible with `base_pke_default()`.
error_t generate_base_pke_rsa_keypair(buf_t& out_ek, buf_t& out_dk);

// Generate a keypair for the built-in ECIES (P-256) base PKE.
//
// Outputs are opaque, versioned byte strings compatible with `base_pke_default()`.
error_t generate_base_pke_ecies_p256_keypair(buf_t& out_ek, buf_t& out_dk);

// Build a built-in ECIES(P-256) base PKE public key blob from an external public key.
//
// This is useful when the private key lives in an HSM (or other external system)
// and only the public key can be exported to software.
//
// Input format:
// - `pub_key_oct` must be the *uncompressed* NIST P-256 public key octet string:
//   65 bytes: 0x04 || X(32) || Y(32).
//
// Output:
// - `out_ek` is an opaque, versioned byte string compatible with:
//   - `base_pke_default()`
//   - `encrypt/verify(...)`
//   - `decrypt_ecies_p256_hsm(...)`
error_t base_pke_ecies_p256_ek_from_oct(mem_t pub_key_oct, buf_t& out_ek);

// Build a built-in RSA-OAEP(2048) base PKE public key blob from a raw modulus.
//
// This is useful when the private key lives in an HSM (or other external system)
// that exports only the raw modulus (e.g. YubiHSM 2).
//
// Input format:
// - `modulus` must be the big-endian RSA modulus (256 bytes for RSA-2048).
// - The public exponent is assumed to be 65537.
//
// Output:
// - `out_ek` is an opaque, versioned byte string compatible with:
//   - `base_pke_default()`
//   - `encrypt/verify(...)`
//   - `decrypt_rsa_oaep_hsm(...)`
error_t base_pke_rsa_ek_from_modulus(mem_t modulus, buf_t& out_ek);

// ---------------------------------------------------------------------------
// Built-in HSM support (KEM decapsulation callback)
// ---------------------------------------------------------------------------

// RSA-OAEP decapsulation callback.
//
// This callback is responsible only for recovering the RSA KEM shared secret
// from `kem_ct` using an HSM-held private key referenced by `dk_handle`.
// The library performs HKDF + AES-GCM DEM and ciphertext parsing.
struct rsa_oaep_hsm_decap_cb_t {
  void* ctx = nullptr;
  error_t (*decap)(void* ctx, mem_t dk_handle, mem_t kem_ct, buf_t& out_kem_ss) = nullptr;
};

// ECIES(P-256) ECDH callback.
//
// This callback should perform the ECDH operation using the HSM-held private
// key referenced by `dk_handle` and the ephemeral public key encoded in `kem_ct`.
// It must output the raw affine-X coordinate as a 32-byte big-endian buffer.
// The library derives the final KEM shared secret and performs HKDF + AES-GCM DEM.
struct ecies_p256_hsm_ecdh_cb_t {
  void* ctx = nullptr;
  error_t (*ecdh)(void* ctx, mem_t dk_handle, mem_t kem_ct, buf_t& out_dh_x32) = nullptr;
};

// Encrypt a scalar `x` under base encryption key `ek`, producing a PVE ciphertext.
//
// - `curve` selects the elliptic curve used for the outer PVE relation (Q = x*G).
// - `label` is associated data that must match in `verify()` / `decrypt()`.
// - `x` is interpreted as a big-endian integer and reduced modulo the curve order.
// - Defensive limit: `x.size` must be <= the curve order size in bytes.
error_t encrypt(const base_pke_i& base_pke, curve_id curve, mem_t ek, mem_t label, mem_t x, buf_t& out_ciphertext);

// Same as `encrypt(...)` using `base_pke_default()`.
error_t encrypt(curve_id curve, mem_t ek, mem_t label, mem_t x, buf_t& out_ciphertext);

// Verify ciphertext validity against the expected public value Q and label.
//
// - `Q_compressed` is the compressed public point encoding for `curve`
//   (33 bytes for P-256/secp256k1, 32 bytes for Ed25519).
error_t verify(const base_pke_i& base_pke, curve_id curve, mem_t ek, mem_t ciphertext, mem_t Q_compressed, mem_t label);

// Same as `verify(...)` using `base_pke_default()`.
error_t verify(curve_id curve, mem_t ek, mem_t ciphertext, mem_t Q_compressed, mem_t label);

// Decrypt a ciphertext, recovering the scalar x.
//
// Output:
// - On success, `out_x` is set to a fixed-length big-endian encoding of x with
//   length equal to the curve order size in bytes (e.g., 32 bytes for P-256).
//
// Notes:
// - This function intentionally does not verify `ciphertext` before decryption.
//   Invalid ciphertexts may cause decryption to fail, but are designed to not
//   leak secret information.
// - If you need ciphertext validation, call `verify(...)` first.
error_t decrypt(const base_pke_i& base_pke, curve_id curve, mem_t dk, mem_t ek, mem_t ciphertext, mem_t label,
                buf_t& out_x);

// Same as `decrypt(...)` using `base_pke_default()`.
error_t decrypt(curve_id curve, mem_t dk, mem_t ek, mem_t ciphertext, mem_t label, buf_t& out_x);

// Decrypt using an HSM-backed RSA private key.
//
// - `dk_handle` is an opaque handle (or identifier) understood by the caller's HSM callback.
// - `ek` is the software public key blob (used for verification and encryption-side checks).
error_t decrypt_rsa_oaep_hsm(curve_id curve, mem_t dk_handle, mem_t ek, mem_t ciphertext, mem_t label,
                             const rsa_oaep_hsm_decap_cb_t& cb, buf_t& out_x);

// Decrypt using an HSM-backed ECIES(P-256) private key.
//
// - `dk_handle` is an opaque handle (or identifier) understood by the caller's HSM callback.
// - `ek` is the software public key blob (used for verification and to derive the KEM context).
error_t decrypt_ecies_p256_hsm(curve_id curve, mem_t dk_handle, mem_t ek, mem_t ciphertext, mem_t label,
                               const ecies_p256_hsm_ecdh_cb_t& cb, buf_t& out_x);

// Extract the public value Q whose discrete log is encrypted as the ciphertext, returning compressed point encoding.
error_t get_public_key_compressed(mem_t ciphertext, buf_t& out_Q_compressed);

// Extract the associated label from a ciphertext.
error_t get_Label(mem_t ciphertext, buf_t& out_label);

}  // namespace coinbase::api::pve
