#include <algorithm>

#include <cbmpc/internal/core/log.h>
#include <cbmpc/internal/crypto/base.h>

namespace coinbase::crypto {

void update_public();
void update_private();

static thread_local paillier_t::rerand_e tls_rerand_mode = paillier_t::rerand_e::off;
paillier_t::rerand_e paillier_t::rerand_scope_t::get() { return tls_rerand_mode; }
void paillier_t::rerand_scope_t::set(paillier_t::rerand_e mode) { tls_rerand_mode = mode; }

void paillier_t::convert(coinbase::converter_t& converter) {
  converter.convert(has_private);
  converter.convert(N);
  if (has_private) {
    converter.convert(p);
    converter.convert(q);
  }

  if (!converter.is_write()) {
    if (converter.is_error()) return;
    if (N.get_bits_count() > bit_size) {
      converter.set_error();
      return;
    }
    if (has_private) {
      // This path rebuilds a private key from serialized state without semantically validating `p`/`q`.
      // It is intended for trusted local blobs.
      update_private();
    } else {
      // This path only rebuilds cached public state from the deserialized modulus.
      // `mod_t::convert()` already enforces the basic modulus representation, but callers are still responsible
      // for any higher-level/context-specific validation at the boundary after deserialization.
      update_public();
    }
  }
}

void paillier_t::generate() {
  // NOTE: This generates Paillier without safe primes since safe primes are only needed for threshold Paillier
  rsa_prv_key_t key;
  key.generate(bit_size);
  p = key.get_p();
  q = key.get_q();

  N = mod_t(p * q, /* multiplicative_dense */ true);

  update_private();
  has_private = true;
}

void paillier_t::update_public() {
  // Internal helper: callers must ensure `N` has already been validated / constructed as a valid `mod_t`.
  // The untrusted-input boundary is handled by `create_pub()` or by `mod_t::convert()` during deserialization.
  // calculate N^2
  NN = mod_t(N * N, /* multiplicative_dense */ true);
}

void paillier_t::update_private() {
  update_public();

  if (p < q) std::swap(p, q);

  // calculating phi(N) = (p-1)(q-1)
  // Side-channel note:
  // This uses generic bignum multiplication on secret primes. The dominant timing signal in typical BN code is
  // operand length (`top`), which is effectively fixed for RSA-2048 primes generated by our keygen. Also, this
  // function is used for key setup (generate/load), not an attacker-triggerable hot path. We understand the
  // general risk of variable-time big integer operations on secrets. Given the fixed operand size here and the
  // non-interactive/offline usage, we consider it acceptable to use generic bignum multiplication in this setup
  // path, even though the operation is not theoretically constant-time.
  phi_N = (p - 1) * (q - 1);

  inv_phi_N = N.inv(phi_N);

  // Precompute N^{-1} mod 2^bit_size for constant-time L(u) extraction during decryption.
  // (See `paillier_t::decrypt` for details.)
  {
    bn_t two_pow = bn_t(1) << bit_size;  // 2^2048
    auto* inv = BN_mod_inverse(inv_N_mod_2k, N.value(), two_pow, bn_t::thread_local_storage_bn_ctx());
    cb_assert(inv && "paillier_t::update_private: failed to invert N mod 2^bit_size");

    constexpr int BN_ULONG_BITS = int(sizeof(BN_ULONG) * 8);
    static_assert(bit_size % BN_ULONG_BITS == 0, "Paillier bit_size must be BN_ULONG-word aligned");
    constexpr int k_words = bit_size / BN_ULONG_BITS;
    BIGNUM& inv_bn = *(BIGNUM*)inv_N_mod_2k;
    cb_assert(bn_wexpand(&inv_bn, k_words));
    // Zero any unused high words and force a fixed-top representation so decrypt can read `d[0..k_words)`.
    for (int i = inv_bn.top; i < k_words; i++) inv_bn.d[i] = 0;
    inv_bn.top = k_words;
    inv_bn.neg = 0;
    inv_bn.flags |= BN_FLG_FIXED_TOP | BN_FLG_CONSTTIME;
  }

  // p^2
  bn_t p_sqr = p * p;

  // q^2
  bn_t q_sqr = q * q;

  // (q^2)^-1 (p^2)
  bn_t q_sqr_inverse = mod_t(p_sqr, /* multiplicative_dense */ true).inv(q_sqr);

  // p^2 - p
  bn_t p_sqr_minus_p = p_sqr - p;

  // q^2 - q
  bn_t q_sqr_minus_q = q_sqr - q;

  bn_t phi_N_mod_p_sqr_minus_p;
  bn_t phi_N_mod_q_sqr_minus_q;
  bn_t N_mod_p_sqr_minus_p;
  bn_t N_mod_q_sqr_minus_q;

  MODULO(LARGEST_PRIME_MOD_2048) {
    // The below calculations are based on the fact that q < p < 2q
    bn_t p_minus_q = p - q;
    phi_N_mod_p_sqr_minus_p = phi_N;
    phi_N_mod_q_sqr_minus_q = (p_minus_q - 1) * (q - 1);
    N_mod_p_sqr_minus_p = N;
    N_mod_q_sqr_minus_q = (p_minus_q + 1) * q;
  }

  crt_dec.p = mod_t(p_sqr, /* multiplicative_dense */ true);
  crt_dec.q = mod_t(q_sqr, /* multiplicative_dense */ true);
  crt_dec.dp = phi_N_mod_p_sqr_minus_p;
  crt_dec.dq = phi_N_mod_q_sqr_minus_q;
  crt_dec.qinv = q_sqr_inverse;

  crt_enc.p = mod_t(p_sqr, /* multiplicative_dense */ true);
  crt_enc.q = mod_t(q_sqr, /* multiplicative_dense */ true);
  crt_enc.dp = N_mod_p_sqr_minus_p;
  crt_enc.dq = N_mod_q_sqr_minus_q;
  crt_enc.qinv = q_sqr_inverse;
}

void paillier_t::create_prv(const bn_t& theN, const bn_t& theP, const bn_t& theQ) {
  N = mod_t(theN, /* multiplicative_dense */ true);
  p = theP;
  q = theQ;
  has_private = true;
  update_private();
}

error_t paillier_t::create_pub(const bn_t& theN) {
  if (!mod_t::is_valid_modulus(theN)) return E_BADARG;
  if (theN.get_bits_count() > bit_size) return E_BADARG;
  N = mod_t(theN, /* multiplicative_dense */ true);
  has_private = false;
  update_public();
  return SUCCESS;
}

bn_t paillier_t::add_ciphers(const bn_t& src1, const bn_t& src2, crypto::paillier_t::rerand_e rerand_mode) const {
  bn_t res;
  MODULO(NN) res = src1 * src2;
  if (rerand_mode == rerand_e::on) res = rerand(res);
  return res;
}

bn_t paillier_t::sub_ciphers(const bn_t& src1, const bn_t& src2, crypto::paillier_t::rerand_e rerand_mode) const {
  bn_t temp = NN.inv(src2);
  bn_t res;
  MODULO(NN) res = src1 * temp;
  if (rerand_mode == rerand_e::on) res = rerand(res);
  return res;
}

bn_t paillier_t::mul_scalar(const bn_t& cipher, const bn_t& scalar, crypto::paillier_t::rerand_e rerand_mode) const {
  bn_t res;
  MODULO(NN) res = cipher.pow(scalar);
  if (rerand_mode == rerand_e::on) res = rerand(res);
  return res;
}

bn_t paillier_t::add_scalar(const bn_t& cipher, const bn_t& scalar, crypto::paillier_t::rerand_e rerand_mode) const {
  bn_t res;
  MODULO(NN) res = cipher * (scalar * N + 1);
  if (rerand_mode == rerand_e::on) res = rerand(res);
  return res;
}

bn_t paillier_t::sub_scalar(const bn_t& cipher, const bn_t& scalar, crypto::paillier_t::rerand_e rerand_mode) const {
  bn_t temp, res;
  MODULO(NN) {
    temp = bn_t(1) - scalar * N;
    res = cipher * temp;
  }

  if (rerand_mode == rerand_e::on) res = rerand(res);
  return res;
}

bn_t paillier_t::sub_cipher_scalar(const bn_t& scalar, const bn_t& cipher,
                                   crypto::paillier_t::rerand_e rerand_mode) const {
  bn_t res;
  bn_t temp = NN.inv(cipher);

  MODULO(NN) { res = (scalar * N + 1) * temp; }

  if (rerand_mode == rerand_e::on) res = rerand(res);
  return res;
}

bn_t paillier_t::encrypt(const bn_t& src) const { return encrypt(src, bn_t::rand(N)); }

bn_t paillier_t::crt_t::compute_power(const bn_t& c, const mod_t& NN) const {
  bn_t c_mod_p = c % p;
  bn_t c_mod_q = c % q;

  bn_t mp, mq;
  MODULO(p) mp = c_mod_p.pow(dp);
  MODULO(q) mq = c_mod_q.pow(dq);

  bn_t h;
  MODULO(p) h = qinv * (mp - mq);
  bn_t dec;
  MODULO(NN) dec = mq + h * q;
  return dec;
}

bn_t paillier_t::encrypt(const bn_t& src, const bn_t& rand) const {
  cb_assert(src >= 0 && src < N && "paillier_t::encrypt: src must be in [0, N)");
  bn_t rn;
  if (has_private) {
    rn = crt_enc.compute_power(rand, NN);
  } else {
    cb_assert(mod_t::coprime(rand, N) && "paillier_t::encrypt: rand and N are not coprime");
    MODULO(NN) rn = rand.pow(N);
  }

  MODULO(NN) rn *= src * N + 1;
  return rn;
}

bn_t paillier_t::decrypt(const bn_t& src) const {
  cb_assert(src > 0 && src < NN && "paillier_t::decrypt: src must be in (0, N^2)");
  cb_assert(mod_t::coprime(src, N) && "paillier_t::decrypt: src must be coprime with N");
  bn_t c1;

  if (has_private) {
    c1 = crt_dec.compute_power(src, NN);
  } else {
    cb_assert(false);
  }

  // Side-channel note:
  // This is the Paillier L(u) step: L(c1) = (c1 - 1) / N, with c1 ∈ Z_{N^2}.
  // For odd N, division by N can be replaced by multiplication with N^{-1} modulo 2^k:
  //   (c1 - 1) = N * L(c1)  ⇒  L(c1) ≡ (c1 - 1) * N^{-1} (mod 2^k)
  // With k = 2048 and 0 ≤ L(c1) < N < 2^k, this recovers L(c1) exactly from the low k bits.
  constexpr int BN_ULONG_BITS = int(sizeof(BN_ULONG) * 8);
  static_assert(bit_size % BN_ULONG_BITS == 0, "Paillier bit_size must be BN_ULONG-word aligned");
  constexpr int k_words = bit_size / BN_ULONG_BITS;

  const BIGNUM& c1_bn = *(const BIGNUM*)c1;
  cb_assert(c1_bn.top >= 0);

  // tmp_low = (c1 - 1) mod 2^k (little-endian words)
  BN_ULONG tmp_low[k_words];
  BN_ULONG borrow = 1;
  for (int i = 0; i < k_words; i++) {
    BN_ULONG w = 0;
    if (i < c1_bn.top) w = c1_bn.d[i];
    tmp_low[i] = w - borrow;
    borrow = (borrow && (w == 0)) ? 1 : 0;
  }

  // m1_words = tmp_low * inv_N_mod_2k mod 2^k
  const BIGNUM& inv_bn = *(const BIGNUM*)inv_N_mod_2k;
  cb_assert(inv_bn.top == k_words);
  BN_ULONG prod[k_words * 2];
  bn_mul_normal(prod, tmp_low, k_words, inv_bn.d, k_words);

  bn_t m1;
  BIGNUM& m1_bn = *(BIGNUM*)m1;
  cb_assert(bn_wexpand(&m1_bn, k_words));
  std::copy(prod, prod + k_words, m1_bn.d);
  m1_bn.top = k_words;
  m1_bn.neg = 0;
  m1_bn.flags |= BN_FLG_FIXED_TOP | BN_FLG_CONSTTIME;

  MODULO(N) m1 *= inv_phi_N;
  return m1;
}

bn_t paillier_t::rerand(const bn_t& cipher) const {
  bn_t r = bn_t::rand(N);

  bn_t rn;
  if (has_private) {
    rn = crt_enc.compute_power(r, NN);
  } else {
    cb_assert(mod_t::coprime(r, N));
    MODULO(NN) rn = r.pow(N);
  }
  MODULO(NN) rn *= cipher;
  return rn;
}

bn_t paillier_t::get_cipher_randomness(const bn_t& plain, const bn_t& cipher) const {
  bn_t c;
  bn_t result;
  bn_t temp = mod_t::N_inv_mod_phiN_2048(N, phi_N);  // temp = 1 / N mod phi_N

  MODULO(NN) { c = cipher / (plain * N + 1); }

  MODULO(N) { result = c.pow(temp); }

  return result;
}

error_t paillier_t::verify_cipher(const mod_t& N, const mod_t& NN, const bn_t& cipher) {
  vartime_scope_t vartime_scope;
  error_t rv = UNINITIALIZED_ERROR;
  if (rv = coinbase::crypto::check_open_range(0, cipher, NN)) return rv;
  if (!mod_t::coprime(cipher, N)) return coinbase::error(E_CRYPTO);
  return SUCCESS;
}
// If the private key is present, we return a single uniform sample in Z_N,
// which lands in Z_N^* with overwhelming probability; otherwise we either
// resample until gcd(r, N) == 1 or return an error.
error_t paillier_t::rand_N_star(bn_t& r, bool resample_until_coprime) const {
  r = bn_t::rand(N);
  if (has_private) return SUCCESS;

  if (mod_t::coprime(r, N)) return SUCCESS;

  if (!resample_until_coprime) {
    r = 0;
    return coinbase::error(E_CRYPTO, "paillier_t::rand_N_star: gcd(r, N) != 1");
  }

  do {
    r = bn_t::rand(N);
  } while (!mod_t::coprime(r, N));
  return SUCCESS;
}

error_t paillier_t::batch_verify_ciphers(const bn_t* ciphers, int n) const {
  if (n == 0) return SUCCESS;
  vartime_scope_t vartime_scope;
  error_t rv = UNINITIALIZED_ERROR;
  for (int i = 0; i < n; i++) {
    if (rv = coinbase::crypto::check_open_range(0, ciphers[i], NN)) return rv;
  }

  bn_t prod = ciphers[0];
  for (int i = 1; i < n; i++) {
    MODULO(N) prod *= ciphers[i];
  }
  if (!mod_t::coprime(prod, N)) return coinbase::error(E_CRYPTO);

  return SUCCESS;
}

}  // namespace coinbase::crypto
