name: "Make release"

on:
  push:
    tags:
      - "cb-mpc-*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
    - name: checkout
      uses: "actions/checkout@v4"
      with:
        fetch-depth: 1
        ref: ${{ github.ref_name }}
        path: ${{ github.ref_name }}

    - name: prepare-assets
      run: |
        cd ${{ github.ref_name }}
        bash scripts/make-release.sh ${{ github.ref_name }}

    - name: attestation
      id: attestation
      uses: "actions/attest-build-provenance@v2"
      with:
        subject-path: ${{ github.ref_name }}/${{ github.ref_name }}.tar.gz

    - name: release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ github.ref_name }} -t "CB-MPC $VERSION" -d --notes " " -R ${{ github.repository }} ${{ github.ref_name }}/${{ github.ref_name }}.tar.gz ${{ steps.attestation.outputs.bundle-path }}
